"""Smart-symbol canvas item (US-C4).

A ``SmartSymbolItem`` is a parametric block: it stores ``symbol_id`` +
``symbol_version`` + ``params`` and **regenerates** its child geometry from a
:class:`SmartSymbolDefinition` rather than storing the expanded shapes. It is a
subclass of :class:`GroupItem`, so it inherits selection/move/rotate, the
type-dispatch sites that treat groups correctly, serialization-of-children, and
DXF export — only the parametric regeneration is new.

Children are built as **generic** shape types (rectangle/polyline/polygon/
circle) so a symbol stays decoupled from the bed/soil/plant systems that key off
``object_type``; the definition's ``object_type`` field is reserved for a future
styling pass. Geometry is generated by the Qt-free ``models.smart_symbol`` and
mapped to items here.
"""

from __future__ import annotations

import logging
import uuid
from typing import Any

from PyQt6.QtCore import QPointF

from open_garden_planner.models.smart_symbol import (
    CircleSpec,
    LineSpec,
    PolygonSpec,
    PolylineSpec,
    PrimitiveSpec,
    RectSpec,
    SmartSymbolError,
)

from .group_item import GroupItem

logger = logging.getLogger(__name__)


class SmartSymbolItem(GroupItem):
    """A parametric block whose children are regenerated from params."""

    def __init__(
        self,
        symbol_id: str,
        symbol_version: int = 1,
        params: dict[str, Any] | None = None,
        layer_id: uuid.UUID | None = None,
        name: str = "",
    ) -> None:
        super().__init__(layer_id=layer_id, name=name)
        self.symbol_id = symbol_id
        self.symbol_version = symbol_version
        self.params: dict[str, Any] = dict(params or {})
        # Last successfully-resolved geometry, kept so a save embeds a snapshot
        # that survives even if the definition is later removed/changed.
        self._cached_specs: list[PrimitiveSpec] | None = None

    def contextMenuEvent(self, event) -> None:
        """Context menu without the inherited Ungroup action.

        Ungrouping a smart symbol would scatter its generated child shapes and
        silently drop the parametric identity (not undoable as a symbol), so it
        is suppressed; only Move to Layer is offered.
        """
        from PyQt6.QtWidgets import QMenu

        menu = QMenu()
        move_layer_menu = self._build_move_to_layer_menu(menu)
        # Arrange submenu (Bring to Front / Forward / Send Backward / Back) —
        # always built, so the menu is never empty (the old isEmpty() guard
        # that papered over a single-layer project is dead now).
        arrange_menu = self._build_arrange_menu(menu)
        action = menu.exec(event.screenPos())
        if move_layer_menu and action and action.parent() is move_layer_menu:
            self._dispatch_move_to_layer(action.data())
        elif arrange_menu and action and action.parent() is arrange_menu:
            self._dispatch_arrange(action.data())

    # ── Geometry ────────────────────────────────────────────────────────────
    def _definition(self):
        from open_garden_planner.services.smart_symbol_library import (
            get_smart_symbol_library,
        )

        return get_smart_symbol_library().get(self.symbol_id)

    def _resolve_specs(self) -> list[PrimitiveSpec]:
        """Resolve the geometry specs: live definition if available + version
        matches, else the cached snapshot (with a warning)."""
        definition = self._definition()
        if definition is not None and definition.version == self.symbol_version:
            try:
                specs = definition.generate(self.params)
                self._cached_specs = specs
                return specs
            except SmartSymbolError as exc:
                # Untrusted JSON: a bad expression, divide-by-zero/overflow, a
                # bad round() arg, or an over-budget repeat must never crash the
                # GUI. generate() funnels every such failure into one type, so
                # the last good geometry (cached) is kept and we warn.
                logger.warning("Smart symbol %s failed to generate: %s", self.symbol_id, exc)
        elif definition is not None:
            logger.warning(
                "Smart symbol %s version mismatch (file v%s, instance v%s) — "
                "using cached geometry.",
                self.symbol_id, definition.version, self.symbol_version,
            )
        elif self._cached_specs is None:
            logger.warning("Smart symbol %s definition not found — using cached geometry.",
                           self.symbol_id)
        if self._cached_specs is not None:
            return self._cached_specs
        # No cache and an unusable/absent definition: best-effort or empty.
        if definition is not None:
            try:
                return definition.generate(self.params)
            except SmartSymbolError:
                return []
        return []

    def regenerate_geometry(self) -> None:
        """Rebuild child primitives from the current params, preserving the
        group's position/rotation/layer."""
        self._clear_children()
        for spec in self._resolve_specs():
            child = _spec_to_item(spec, self.layer_id)
            if child is not None:
                self.addToGroup(child)

    def set_cached_specs(self, specs: list[PrimitiveSpec]) -> None:
        """Seed the fallback snapshot (used when loading a file whose definition
        is missing or version-mismatched, before building children from it)."""
        self._cached_specs = list(specs)

    def _clear_children(self) -> None:
        for child in list(self.childItems()):
            child.setParentItem(None)
            scene = child.scene()
            if scene is not None:
                scene.removeItem(child)


def _spec_to_item(spec: PrimitiveSpec, layer_id: uuid.UUID | None):
    """Map a Qt-free geometry spec to a concrete generic shape item."""
    from open_garden_planner.core.object_types import ObjectType
    from open_garden_planner.ui.canvas.items.circle_item import CircleItem
    from open_garden_planner.ui.canvas.items.polygon_item import PolygonItem
    from open_garden_planner.ui.canvas.items.polyline_item import PolylineItem
    from open_garden_planner.ui.canvas.items.rectangle_item import RectangleItem

    if isinstance(spec, RectSpec):
        return RectangleItem(
            spec.x, spec.y, spec.w, spec.h,
            object_type=ObjectType.GENERIC_RECTANGLE, layer_id=layer_id,
        )
    if isinstance(spec, LineSpec):
        return PolylineItem(
            [QPointF(spec.x1, spec.y1), QPointF(spec.x2, spec.y2)],
            object_type=ObjectType.FENCE, layer_id=layer_id,
        )
    if isinstance(spec, PolylineSpec):
        return PolylineItem(
            [QPointF(x, y) for x, y in spec.points],
            object_type=ObjectType.FENCE, layer_id=layer_id,
        )
    if isinstance(spec, PolygonSpec):
        return PolygonItem(
            [QPointF(x, y) for x, y in spec.points],
            object_type=ObjectType.GENERIC_POLYGON, layer_id=layer_id,
        )
    if isinstance(spec, CircleSpec):
        return CircleItem(
            spec.cx, spec.cy, spec.r,
            object_type=ObjectType.GENERIC_CIRCLE, layer_id=layer_id,
        )
    return None
