"""Pinned-number tests for the Qt-free solar position engine (US-E1, #256).

Every number here traces to one of two provenances:

1. ORACLE ROWS — generated by the campaign oracle
   ``.claude/skills/ogp-3d-sunshade-campaign/scripts/solar_reference.py``
   (regenerated 2026-07-04, ALL CHECKS PASSED). Tolerance ±0.05° because
   production copies the same algorithm verbatim — these rows pin against
   *drift*, not against the outside world.

2. EXTERNAL / PHYSICAL ROWS — independently published facts (textbook
   example, almanac extremes, physical identities), each with a provenance
   comment. Tolerance ±0.5° / ±0.5 min — the campaign accuracy claim
   (ADR-037). These are the third-party validation the oracle rows cannot
   provide.

   NOTE: live NOAA/USNO cross-check endpoints (gml.noaa.gov solcalc,
   aa.usno.navy.mil) were unreachable from the implementation sandbox
   (network policy). Anyone with browser access is welcome to append more
   rows from the NOAA Solar Calculator — the format below shows how.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

import pytest

from open_garden_planner.core.solar import SolarPosition, solar_position

BERLIN = (52.52, 13.405)
EQUATOR = (0.0, 0.0)


def _at(lat_lon: tuple[float, float], *args: int) -> SolarPosition:
    lat, lon = lat_lon
    return solar_position(lat, lon, datetime(*args, tzinfo=UTC))


# ---------------------------------------------------------------------------
# 1. Oracle gate table (±0.05° vs the shipped oracle — same algorithm)
# ---------------------------------------------------------------------------

# (location, datetime args, elev, elev_refr, azimuth, decl, eot_minutes)
ORACLE_ROWS = [
    (BERLIN, (2026, 6, 21, 12, 0), 59.29, 59.30, 203.74, 23.44, -1.82),
    (BERLIN, (2026, 12, 21, 12, 0), 13.08, 13.15, 193.06, -23.44, 1.92),
    (EQUATOR, (2026, 3, 20, 12, 0), 88.14, 88.14, 91.34, -0.04, -7.43),
    (EQUATOR, (2026, 6, 21, 12, 0), 66.56, 66.56, 1.05, 23.44, -1.82),
]


@pytest.mark.parametrize("loc, when, elev, elev_refr, az, decl, eot", ORACLE_ROWS)
def test_oracle_gate_table(loc, when, elev, elev_refr, az, decl, eot):
    pos = _at(loc, *when)
    assert pos.elevation_deg == pytest.approx(elev, abs=0.05)
    assert pos.elevation_refracted_deg == pytest.approx(elev_refr, abs=0.05)
    assert pos.azimuth_deg == pytest.approx(az, abs=0.05)
    assert pos.declination_deg == pytest.approx(decl, abs=0.05)
    assert pos.eot_minutes == pytest.approx(eot, abs=0.05)


# ---------------------------------------------------------------------------
# 2. External literature row (independent of the oracle file)
# ---------------------------------------------------------------------------


def test_meeus_example_25a_declination():
    """Meeus, *Astronomical Algorithms*, 2nd ed., Example 25.a (p. 165).

    Sun position for 1992 October 13.0 TD; the book prints the apparent
    declination as delta = -7.78507 deg (-7deg 47' 06").  TD (Terrestrial
    Dynamical Time) leads UTC by ~58 s in 1992 — the sun's declination
    changes ~0.9 deg/day in October, so the TD/UTC gap contributes < 0.001
    deg, far inside the tolerance.  This row is the published-literature
    anchor: it validates the implementation against the book's own printed
    result rather than against our oracle script.
    """
    pos = solar_position(0.0, 0.0, datetime(1992, 10, 13, 0, 0, tzinfo=UTC))
    assert pos.declination_deg == pytest.approx(-7.78507, abs=0.01)


# ---------------------------------------------------------------------------
# 3. Physical-identity checks (externally documented facts, not our numbers)
# ---------------------------------------------------------------------------


def test_declination_extremes_match_axial_tilt():
    """Earth's axial tilt is 23.44 deg (published constant): the solstice
    declinations must hit +/-23.44 deg."""
    summer = _at(BERLIN, 2026, 6, 21, 12, 0)
    winter = _at(BERLIN, 2026, 12, 21, 12, 0)
    assert summer.declination_deg == pytest.approx(23.44, abs=0.02)
    assert winter.declination_deg == pytest.approx(-23.44, abs=0.02)


def _max_elevation_on(loc: tuple[float, float], year: int, month: int, day: int) -> float:
    """Scan a day at 1-minute steps for the maximum geometric elevation."""
    lat, lon = loc
    best = -90.0
    t = datetime(year, month, day, 0, 0, tzinfo=UTC)
    for _ in range(1440):
        best = max(best, solar_position(lat, lon, t).elevation_deg)
        t += timedelta(minutes=1)
    return best


def test_solstice_noon_elevation_identity():
    """Spherical-geometry identity: max elevation = 90 - |lat - decl|.

    Berlin summer: 90 - |52.52 - 23.44| = 60.92; winter: 90 - |52.52 + 23.44|
    = 14.04. This is textbook geometry, independent of any implementation.
    """
    assert _max_elevation_on(BERLIN, 2026, 6, 21) == pytest.approx(60.92, abs=0.05)
    assert _max_elevation_on(BERLIN, 2026, 12, 21) == pytest.approx(14.04, abs=0.05)


def test_equation_of_time_extremes():
    """Almanac facts: EoT reaches ~-14.2 min in mid-February and ~+16.4 min
    in early November (e.g. any astronomical almanac / analemma table)."""
    feb = _at(BERLIN, 2026, 2, 11, 12, 0)
    nov = _at(BERLIN, 2026, 11, 3, 12, 0)
    assert feb.eot_minutes == pytest.approx(-14.2, abs=0.5)
    assert nov.eot_minutes == pytest.approx(16.4, abs=0.5)


def test_equinox_sunrise_azimuth_due_east():
    """On the equinox the sun rises due east (azimuth ~90 deg) at any
    latitude — a published physical fact. Scan for the sunrise minute in
    Berlin on 2026-03-20 and check its azimuth."""
    lat, lon = BERLIN
    t = datetime(2026, 3, 20, 0, 0, tzinfo=UTC)
    prev_up = solar_position(lat, lon, t).is_sun_up
    sunrise_az = None
    for _ in range(1440):
        t += timedelta(minutes=1)
        pos = solar_position(lat, lon, t)
        if pos.is_sun_up and not prev_up:
            sunrise_az = pos.azimuth_deg
            break
        prev_up = pos.is_sun_up
    assert sunrise_az is not None
    assert sunrise_az == pytest.approx(90.0, abs=0.5)


def test_northern_solar_noon_azimuth_south():
    """Northern mid-latitudes: at the hour-angle zero crossing the sun is
    due south (azimuth 180) — the classic quadrant-bug detector."""
    lat, lon = BERLIN
    best = min(
        (
            solar_position(lat, lon, datetime(2026, 6, 21, 12, 0, tzinfo=UTC) - timedelta(minutes=m))
            for m in range(-120, 120)
        ),
        key=lambda p: abs(p.hour_angle_deg),
    )
    assert best.azimuth_deg == pytest.approx(180.0, abs=0.5)


# ---------------------------------------------------------------------------
# 4. API contract
# ---------------------------------------------------------------------------


def test_naive_datetime_raises():
    with pytest.raises(ValueError, match="timezone-aware"):
        solar_position(52.52, 13.405, datetime(2026, 6, 21, 12, 0))


def test_non_utc_timezone_is_normalized():
    """A CEST-aware datetime must give the identical result as its UTC
    equivalent (14:00 CEST == 12:00 UTC)."""
    from datetime import timezone as _tz

    cest = _tz(timedelta(hours=2))
    a = solar_position(*BERLIN, datetime(2026, 6, 21, 14, 0, tzinfo=cest))
    b = _at(BERLIN, 2026, 6, 21, 12, 0)
    assert a.elevation_deg == pytest.approx(b.elevation_deg, abs=1e-9)
    assert a.azimuth_deg == pytest.approx(b.azimuth_deg, abs=1e-9)


def test_zenith_no_singularity():
    """Equator equinox noon: sun within ~2 deg of the zenith. The acos
    azimuth formulation blows up here; the atan2 form must return a finite
    azimuth and a ~88 deg elevation."""
    pos = _at(EQUATOR, 2026, 3, 20, 12, 0)
    assert pos.elevation_deg > 85.0
    assert 0.0 <= pos.azimuth_deg < 360.0


def test_is_sun_up_flag():
    assert _at(BERLIN, 2026, 6, 21, 12, 0).is_sun_up
    assert not _at(BERLIN, 2026, 6, 21, 23, 30).is_sun_up


def test_dataclass_is_frozen():
    pos = _at(BERLIN, 2026, 6, 21, 12, 0)
    with pytest.raises(AttributeError):
        pos.elevation_deg = 0.0  # type: ignore[misc]
