"""Unit tests for the Qt-free shadow geometry core (US-E3, #258).

Every pinned number is oracle-sourced (campaign skill appendix, generated by
``scripts/solar_reference.py`` — ALL CHECKS PASSED 2026-07-19):

- Berlin 2026-06-21 12:00 UTC → α = 59.29°, Az = 203.74°,
  100 cm object → L = 59.4 cm, direction (+0.4025, +0.9154) (NNE, +y = North)
- Berlin 2026-12-21 12:00 UTC → α = 13.08°, Az = 193.06°,
  100 cm object → L = 430.4 cm, direction (+0.226, +0.974)
"""

from __future__ import annotations

import math

import pytest

from open_garden_planner.core.shadow_geometry import (
    MIN_SUN_ELEVATION_DEG,
    circle_footprint,
    compute_scene_shadows,
    polyline_footprint,
    shadow_direction_scene,
    shadow_length_cm,
    shadow_polygon,
    union_shadows,
)

# ── helpers (test-local, dumb on purpose) ────────────────────────────


def signed_area(polygon) -> float:
    """Shoelace: positive for CCW, negative for CW (holes)."""
    total = 0.0
    n = len(polygon)
    for i in range(n):
        x1, y1 = polygon[i]
        x2, y2 = polygon[(i + 1) % n]
        total += x1 * y2 - x2 * y1
    return total / 2.0


def net_area(polygons) -> float:
    """Sum of signed areas — outers add, holes subtract."""
    return sum(signed_area(p) for p in polygons)


def point_in_polygons(point, polygons) -> bool:
    """Even-odd ray cast over all rings (matches the overlay's fill rule)."""
    x, y = point
    inside = False
    for polygon in polygons:
        n = len(polygon)
        for i in range(n):
            x1, y1 = polygon[i]
            x2, y2 = polygon[(i + 1) % n]
            if (y1 > y) != (y2 > y):
                x_cross = x1 + (y - y1) * (x2 - x1) / (y2 - y1)
                if x_cross > x:
                    inside = not inside
    return inside


SQUARE = [(100.0, 100.0), (140.0, 100.0), (140.0, 140.0), (100.0, 140.0)]


class TestShadowLength:
    def test_berlin_summer_noon_pinned(self) -> None:
        assert shadow_length_cm(100.0, 59.29) == pytest.approx(59.4, abs=0.1)

    def test_berlin_winter_noon_pinned(self) -> None:
        assert shadow_length_cm(100.0, 13.08) == pytest.approx(430.4, abs=1.0)

    def test_sun_below_horizon_is_none(self) -> None:
        assert shadow_length_cm(100.0, 0.0) is None
        assert shadow_length_cm(100.0, -12.0) is None

    def test_grazing_sun_below_threshold_is_none(self) -> None:
        assert shadow_length_cm(100.0, MIN_SUN_ELEVATION_DEG - 0.1) is None

    def test_no_height_is_none(self) -> None:
        assert shadow_length_cm(None, 45.0) is None
        assert shadow_length_cm(0.0, 45.0) is None
        assert shadow_length_cm(-5.0, 45.0) is None

    def test_zenith_sun_casts_nothing(self) -> None:
        assert shadow_length_cm(100.0, 90.0) == pytest.approx(0.0, abs=1e-9)


class TestShadowDirection:
    def test_berlin_summer_noon_pinned(self) -> None:
        dx, dy = shadow_direction_scene(203.74)
        assert dx == pytest.approx(0.4025, abs=0.01)
        assert dy == pytest.approx(0.9154, abs=0.01)

    def test_berlin_winter_noon_pinned(self) -> None:
        dx, dy = shadow_direction_scene(193.06)
        assert dx == pytest.approx(0.226, abs=0.01)
        assert dy == pytest.approx(0.974, abs=0.01)

    def test_south_sun_shadow_points_north(self) -> None:
        dx, dy = shadow_direction_scene(180.0)
        assert dx == pytest.approx(0.0, abs=1e-12)
        assert dy == pytest.approx(1.0)  # +y = North — NO extra flip

    def test_east_sun_shadow_points_west(self) -> None:
        dx, dy = shadow_direction_scene(90.0)
        assert dx == pytest.approx(-1.0)
        assert dy == pytest.approx(0.0, abs=1e-12)

    def test_unit_length(self) -> None:
        for az in (0.0, 51.3, 90.0, 193.06, 270.0, 359.9):
            dx, dy = shadow_direction_scene(az)
            assert math.hypot(dx, dy) == pytest.approx(1.0)


class TestFootprints:
    def test_circle_footprint_radius_and_count(self) -> None:
        poly = circle_footprint(50.0, 60.0, 30.0, segments=24)
        assert len(poly) == 24
        for x, y in poly:
            assert math.hypot(x - 50.0, y - 60.0) == pytest.approx(30.0)

    def test_circle_footprint_degenerate(self) -> None:
        assert circle_footprint(0, 0, 0.0) == []
        assert circle_footprint(0, 0, -3.0) == []

    def test_polyline_inflation_area(self) -> None:
        # 400 cm straight fence, 4 cm stroke → ~1600 cm² footprint (butt ends).
        polys = polyline_footprint([(0.0, 0.0), (400.0, 0.0)], 4.0)
        assert len(polys) == 1
        assert abs(net_area(polys)) == pytest.approx(1600.0, rel=0.02)

    def test_polyline_degenerate(self) -> None:
        assert polyline_footprint([(0.0, 0.0)], 4.0) == []
        assert polyline_footprint([(0.0, 0.0), (100.0, 0.0)], 0.0) == []


class TestShadowPolygon:
    def test_south_sun_sweeps_square_north(self) -> None:
        # Sun due south at 45°, height 100 → L = 100, sweep straight north:
        # 40×40 square becomes a 40×140 rectangle. Area is exact.
        polys = shadow_polygon(SQUARE, 100.0, 45.0, 180.0)
        assert polys
        assert net_area(polys) == pytest.approx(40.0 * 140.0, rel=0.001)
        xs = [x for p in polys for x, _ in p]
        ys = [y for p in polys for _, y in p]
        assert min(xs) == pytest.approx(100.0, abs=0.01)
        assert max(xs) == pytest.approx(140.0, abs=0.01)
        assert min(ys) == pytest.approx(100.0, abs=0.01)
        assert max(ys) == pytest.approx(240.0, abs=0.01)

    def test_berlin_summer_tip_location(self) -> None:
        # The binding direction fact, in pure geometry: the shadow tip of the
        # NE corner lies at corner + L·(+0.4025, +0.9154) — north-north-east.
        polys = shadow_polygon(SQUARE, 100.0, 59.29, 203.74)
        length = shadow_length_cm(100.0, 59.29)
        dx, dy = shadow_direction_scene(203.74)
        tip = (140.0 + dx * length, 140.0 + dy * length)
        just_inside = (tip[0] - dx * 2.0, tip[1] - dy * 2.0)
        just_beyond = (tip[0] + dx * 2.0, tip[1] + dy * 2.0)
        assert point_in_polygons(just_inside, polys)
        assert not point_in_polygons(just_beyond, polys)
        assert tip[1] > 140.0  # tip went NORTH (+y), the un-mirrored direction

    def test_night_returns_empty(self) -> None:
        assert shadow_polygon(SQUARE, 100.0, -5.0, 180.0) == []

    def test_degenerate_footprint_returns_empty(self) -> None:
        assert shadow_polygon([(0.0, 0.0), (10.0, 0.0)], 100.0, 45.0, 180.0) == []

    def test_zenith_shadow_is_footprint(self) -> None:
        polys = shadow_polygon(SQUARE, 100.0, 90.0, 180.0)
        assert net_area(polys) == pytest.approx(1600.0, rel=0.001)

    def test_minkowski_and_fallback_agree(self, monkeypatch) -> None:
        import pyclipper

        import open_garden_planner.core.shadow_geometry as sg

        reference = shadow_polygon(SQUARE, 100.0, 59.29, 203.74)

        def _raise(*_args, **_kwargs):
            raise pyclipper.ClipperException("probe: MinkowskiSum unavailable")

        monkeypatch.setattr(pyclipper, "MinkowskiSum", _raise)
        fallback = sg.shadow_polygon(SQUARE, 100.0, 59.29, 203.74)
        # The 8-step staircase fallback is the spec's "visually identical at
        # garden scale" approximation — a few % of area in cm-scale edge
        # notches, with the tip and direction exact.
        assert net_area(fallback) == pytest.approx(net_area(reference), rel=0.05)
        length = shadow_length_cm(100.0, 59.29)
        dx, dy = shadow_direction_scene(203.74)
        tip = (140.0 + dx * length, 140.0 + dy * length)
        assert point_in_polygons((tip[0] - dx * 2.0, tip[1] - dy * 2.0), fallback)
        assert not point_in_polygons((tip[0] + dx * 2.0, tip[1] + dy * 2.0), fallback)


class TestUnionAndScene:
    def test_overlapping_shadows_union_to_one(self) -> None:
        a = [(0.0, 0.0), (100.0, 0.0), (100.0, 100.0), (0.0, 100.0)]
        b = [(50.0, 50.0), (150.0, 50.0), (150.0, 150.0), (50.0, 150.0)]
        merged = union_shadows([a, b])
        assert len(merged) == 1
        assert net_area(merged) == pytest.approx(100 * 100 * 2 - 50 * 50, rel=0.001)

    def test_disjoint_shadows_stay_separate(self) -> None:
        a = [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0)]
        b = [(100.0, 100.0), (110.0, 100.0), (110.0, 110.0), (100.0, 110.0)]
        assert len(union_shadows([a, b])) == 2

    def test_compute_scene_shadows_unions_casters(self) -> None:
        # Two identical adjacent squares under a due-south sun merge into one
        # connected shadow band.
        a = [(0.0, 0.0), (40.0, 0.0), (40.0, 40.0), (0.0, 40.0)]
        b = [(30.0, 0.0), (70.0, 0.0), (70.0, 40.0), (30.0, 40.0)]
        polys = compute_scene_shadows([(a, 100.0), (b, 100.0)], 45.0, 180.0)
        outers = [p for p in polys if signed_area(p) > 0]
        assert len(outers) == 1
        assert net_area(polys) == pytest.approx(70.0 * 140.0, rel=0.001)

    def test_compute_scene_shadows_at_night_is_empty(self) -> None:
        assert compute_scene_shadows([(SQUARE, 100.0)], -3.0, 180.0) == []

    def test_caster_without_height_is_skipped(self) -> None:
        polys = compute_scene_shadows(
            [(SQUARE, None), (SQUARE, 0.0)], 45.0, 180.0
        )
        assert polys == []

    def test_clockwise_footprint_is_normalized(self) -> None:
        cw_square = list(reversed(SQUARE))
        polys = shadow_polygon(cw_square, 100.0, 45.0, 180.0)
        assert net_area(polys) == pytest.approx(40.0 * 140.0, rel=0.001)
